export { authAPI } from './endpoints/auth'
export { menuAPI } from './endpoints/menu'
export { ordersAPI } from './endpoints/orders'
export { cartAPI } from './endpoints/cart'
export { deliveryAPI } from './endpoints/delivery'
export { paymentsAPI } from './endpoints/payments'
export { notificationsAPI } from './endpoints/notifications'
export { adminAPI } from './endpoints/admin'
export { contactAPI } from './endpoints/contact'

export { default as apiClient } from './client'
